const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcryptjs");
const prisma = new PrismaClient();
async function main() {
  console.log("Iniciando seed...");
  var settings = await prisma.companySettings.create({ data: { companyName: "NovaTech Bolivia S.R.L.", taxId: "1023456789", address: "Av. Arce #2345, La Paz", phone: "+591 2 2441234", email: "rrhh@novatech.bo", workHoursStart: "08:00", workHoursEnd: "18:00", currency: "BOB" } });
  await Promise.all([prisma.branch.create({ data: { name: "Oficina Central La Paz", address: "Av. Arce #2345", phone: "+591 2 2441234", city: "La Paz", isMain: true } }), prisma.branch.create({ data: { name: "Sucursal Santa Cruz", address: "Av. Cristo Redentor #890", phone: "+591 3 3561234", city: "Santa Cruz" } }), prisma.branch.create({ data: { name: "Sucursal Cochabamba", address: "Av. Ayacucho #456", phone: "+591 4 4251234", city: "Cochabamba" } })]);
  var deps = await Promise.all([prisma.department.create({ data: { name: "Tecnologia", code: "TEC", description: "Desarrollo de software", budget: 150000 } }), prisma.department.create({ data: { name: "Recursos Humanos", code: "RRHH", description: "Gestion del talento", budget: 80000 } }), prisma.department.create({ data: { name: "Ventas", code: "VEN", description: "Comercializacion", budget: 120000 } }), prisma.department.create({ data: { name: "Marketing", code: "MKT", description: "Estrategia de marca", budget: 95000 } }), prisma.department.create({ data: { name: "Finanzas", code: "FIN", description: "Contabilidad", budget: 100000 } }), prisma.department.create({ data: { name: "Operaciones", code: "OPS", description: "Logistica", budget: 110000 } }), prisma.department.create({ data: { name: "Legal", code: "LEG", description: "Asesoria juridica", budget: 60000 } }), prisma.department.create({ data: { name: "Atencion al Cliente", code: "ATC", description: "Soporte al cliente", budget: 75000 } })]);
  var pos = await Promise.all([prisma.position.create({ data: { title: "Gerente de Tecnologia", code: "GT-001", departmentId: deps[0].id, salaryMin: 12000, salaryMax: 18000 } }), prisma.position.create({ data: { title: "Desarrollador Senior", code: "DS-001", departmentId: deps[0].id, salaryMin: 8000, salaryMax: 14000 } }), prisma.position.create({ data: { title: "Desarrollador Junior", code: "DJ-001", departmentId: deps[0].id, salaryMin: 4000, salaryMax: 7000 } }), prisma.position.create({ data: { title: "QA Engineer", code: "QA-001", departmentId: deps[0].id, salaryMin: 5000, salaryMax: 9000 } }), prisma.position.create({ data: { title: "Gerente de RRHH", code: "GR-001", departmentId: deps[1].id, salaryMin: 10000, salaryMax: 16000 } }), prisma.position.create({ data: { title: "Analista de RRHH", code: "AR-001", departmentId: deps[1].id, salaryMin: 5000, salaryMax: 8000 } }), prisma.position.create({ data: { title: "Director Comercial", code: "DC-001", departmentId: deps[2].id, salaryMin: 11000, salaryMax: 17000 } }), prisma.position.create({ data: { title: "Ejecutivo de Ventas", code: "EV-001", departmentId: deps[2].id, salaryMin: 4500, salaryMax: 8000 } }), prisma.position.create({ data: { title: "Community Manager", code: "CM-001", departmentId: deps[3].id, salaryMin: 4000, salaryMax: 7000 } }), prisma.position.create({ data: { title: "Disenador Grafico", code: "DG-001", departmentId: deps[3].id, salaryMin: 4500, salaryMax: 7500 } }), prisma.position.create({ data: { title: "Contador General", code: "CG-001", departmentId: deps[4].id, salaryMin: 7000, salaryMax: 12000 } }), prisma.position.create({ data: { title: "Asistente Contable", code: "AC-001", departmentId: deps[4].id, salaryMin: 3500, salaryMax: 6000 } }), prisma.position.create({ data: { title: "Jefe de Operaciones", code: "JO-001", departmentId: deps[5].id, salaryMin: 9000, salaryMax: 14000 } }), prisma.position.create({ data: { title: "Abogado Corporativo", code: "AB-001", departmentId: deps[6].id, salaryMin: 8000, salaryMax: 13000 } }), prisma.position.create({ data: { title: "Agente de Soporte", code: "AS-001", departmentId: deps[7].id, salaryMin: 3500, salaryMax: 5500 } })]);
  var leaveTypes = await Promise.all([prisma.leaveType.create({ data: { name: "Vacacion Anual", daysPerYear: 15, isPaid: true } }), prisma.leaveType.create({ data: { name: "Licencia por Enfermedad", daysPerYear: 26, isPaid: true } }), prisma.leaveType.create({ data: { name: "Licencia por Maternidad", daysPerYear: 90, isPaid: true } }), prisma.leaveType.create({ data: { name: "Licencia por Paternidad", daysPerYear: 3, isPaid: true } }), prisma.leaveType.create({ data: { name: "Duelo Familiar", daysPerYear: 3, isPaid: true } }), prisma.leaveType.create({ data: { name: "Matrimonio", daysPerYear: 3, isPaid: true } }), prisma.leaveType.create({ data: { name: "Permiso Personal", daysPerYear: 5, isPaid: false } }), prisma.leaveType.create({ data: { name: "Estudio / Examen", daysPerYear: 5, isPaid: true } })]);
  var hash = await bcrypt.hash("admin123", 10);
  var adminUser = await prisma.user.create({ data: { email: "admin@novatech.bo", password: hash, name: "Administrador", role: "ADMIN" } });
  var hrUser = await prisma.user.create({ data: { email: "rrhh@novatech.bo", password: hash, name: "Maria Elena Quispe", role: "HR_MANAGER" } });
  var mgrUser = await prisma.user.create({ data: { email: "gerente@novatech.bo", password: hash, name: "Carlos Mamani Lopez", role: "MANAGER" } });
  var empData = [
    { fn:"Maria Elena",ln:"Quispe Huanca",em:"maria.quispe@novatech.bo",ph:"+591 71234567",nid:"4567890 LP",g:"FEMENINO",bd:"1988-03-15",addr:"La Paz",pi:4,di:1,sal:12000,hd:"2020-01-15",uid:hrUser.id },
    { fn:"Carlos",ln:"Mamani Lopez",em:"carlos.mamani@novatech.bo",ph:"+591 72345678",nid:"5678901 LP",g:"MASCULINO",bd:"1985-07-22",addr:"La Paz",pi:0,di:0,sal:15000,hd:"2019-06-01",uid:mgrUser.id },
    { fn:"Ana Lucia",ln:"Fernandez Rojas",em:"ana.fernandez@novatech.bo",ph:"+591 73456789",nid:"6789012 SC",g:"FEMENINO",bd:"1992-11-08",addr:"Santa Cruz",pi:1,di:0,sal:10000,hd:"2021-03-10" },
    { fn:"Diego",ln:"Choque Condori",em:"diego.choque@novatech.bo",ph:"+591 74567890",nid:"7890123 LP",g:"MASCULINO",bd:"1995-05-20",addr:"La Paz",pi:2,di:0,sal:5500,hd:"2023-01-15" },
    { fn:"Paola",ln:"Vargas Mendoza",em:"paola.vargas@novatech.bo",ph:"+591 75678901",nid:"8901234 CB",g:"FEMENINO",bd:"1990-09-12",addr:"Cochabamba",pi:6,di:2,sal:13000,hd:"2020-08-01" },
    { fn:"Roberto",ln:"Gutierrez Flores",em:"roberto.gutierrez@novatech.bo",ph:"+591 76789012",nid:"9012345 SC",g:"MASCULINO",bd:"1987-01-30",addr:"Santa Cruz",pi:7,di:2,sal:6000,hd:"2022-04-20" },
    { fn:"Luciana",ln:"Torrez Apaza",em:"luciana.torrez@novatech.bo",ph:"+591 77890123",nid:"0123456 LP",g:"FEMENINO",bd:"1993-12-05",addr:"La Paz",pi:8,di:3,sal:5000,hd:"2022-09-01" },
    { fn:"Fernando",ln:"Salazar Rios",em:"fernando.salazar@novatech.bo",ph:"+591 78901234",nid:"1234560 LP",g:"MASCULINO",bd:"1986-04-18",addr:"La Paz",pi:10,di:4,sal:9000,hd:"2019-11-15" },
    { fn:"Gabriela",ln:"Poma Escobar",em:"gabriela.poma@novatech.bo",ph:"+591 79012345",nid:"2345671 CB",g:"FEMENINO",bd:"1994-08-25",addr:"Cochabamba",pi:11,di:4,sal:4500,hd:"2023-06-01" },
    { fn:"Javier",ln:"Medina Quiroga",em:"javier.medina@novatech.bo",ph:"+591 70123456",nid:"3456782 SC",g:"MASCULINO",bd:"1989-02-14",addr:"Santa Cruz",pi:12,di:5,sal:11000,hd:"2020-05-01" },
    { fn:"Carla",ln:"Nina Alanoca",em:"carla.nina@novatech.bo",ph:"+591 71122334",nid:"4567893 LP",g:"FEMENINO",bd:"1991-06-10",addr:"La Paz",pi:5,di:1,sal:6500,hd:"2021-10-01" },
    { fn:"Miguel",ln:"Rojas Cuellar",em:"miguel.rojas@novatech.bo",ph:"+591 72233445",nid:"5678904 SC",g:"MASCULINO",bd:"1996-10-03",addr:"Santa Cruz",pi:3,di:0,sal:6000,hd:"2023-03-15" },
    { fn:"Valentina",ln:"Coca Limachi",em:"valentina.coca@novatech.bo",ph:"+591 73344556",nid:"6789015 LP",g:"FEMENINO",bd:"1997-07-28",addr:"La Paz",pi:9,di:3,sal:5500,hd:"2022-07-01" },
    { fn:"Andres",ln:"Callisaya Mamani",em:"andres.callisaya@novatech.bo",ph:"+591 74455667",nid:"7890126 LP",g:"MASCULINO",bd:"1984-11-17",addr:"El Alto",pi:13,di:6,sal:9500,hd:"2020-02-01" },
    { fn:"Sofia",ln:"Pacheco Vega",em:"sofia.pacheco@novatech.bo",ph:"+591 75566778",nid:"8901237 CB",g:"FEMENINO",bd:"1998-03-09",addr:"Cochabamba",pi:14,di:7,sal:4000,hd:"2024-01-15" },
    { fn:"Hector",ln:"Colque Aruquipa",em:"hector.colque@novatech.bo",ph:"+591 76677889",nid:"9012348 LP",g:"MASCULINO",bd:"1993-09-21",addr:"La Paz",pi:1,di:0,sal:9000,hd:"2021-05-15" },
    { fn:"Daniela",ln:"Espinoza Aguilar",em:"daniela.espinoza@novatech.bo",ph:"+591 77788990",nid:"0123459 SC",g:"FEMENINO",bd:"1990-12-01",addr:"Santa Cruz",pi:7,di:2,sal:5500,hd:"2022-11-01" },
    { fn:"Ricardo",ln:"Yujra Chura",em:"ricardo.yujra@novatech.bo",ph:"+591 78899001",nid:"1234562 LP",g:"MASCULINO",bd:"1988-06-15",addr:"El Alto",pi:2,di:0,sal:6000,hd:"2022-02-01" },
    { fn:"Camila",ln:"Arce Montano",em:"camila.arce@novatech.bo",ph:"+591 79900112",nid:"2345673 CB",g:"FEMENINO",bd:"1995-01-25",addr:"Cochabamba",pi:8,di:3,sal:4800,hd:"2023-08-01" },
    { fn:"Luis",ln:"Pinto Camacho",em:"luis.pinto@novatech.bo",ph:"+591 70011223",nid:"3456784 SC",g:"MASCULINO",bd:"1991-04-07",addr:"Santa Cruz",pi:14,di:7,sal:4200,hd:"2023-11-01" }
  ];
  var employees = [];
  for (var i = 0; i < empData.length; i++) { var d = empData[i]; var code = "NT-" + String(i+1).padStart(5,"0"); var ct = i < 10 ? "INDEFINIDO" : i < 16 ? "PLAZO_FIJO" : "EVENTUAL"; var emp = await prisma.employee.create({ data: { employeeCode: code, firstName: d.fn, lastName: d.ln, email: d.em, phone: d.ph, nationalId: d.nid, gender: d.g, birthDate: new Date(d.bd), address: d.addr, positionId: pos[d.pi].id, departmentId: deps[d.di].id, salary: d.sal, hireDate: new Date(d.hd), contractType: ct, isActive: true } }); employees.push(emp); if (d.uid) await prisma.user.update({ where: { id: d.uid }, data: { employeeId: emp.id } }); }
  console.log(employees.length + " empleados");
  for (var ci2 = 0; ci2 < 10; ci2++) { var emp0 = employees[ci2]; var rels = ["Madre","Padre","Hermano/a","Esposo/a"]; await prisma.emergencyContact.create({ data: { employeeId: emp0.id, name: "Familiar de " + emp0.firstName, relationship: rels[ci2 % 4], phone: "+591 7" + Math.floor(1000000 + Math.random()*9000000) } }); }
  for (var ci3 = 0; ci3 < employees.length; ci3++) { var emp1 = employees[ci3]; await prisma.contract.create({ data: { employeeId: emp1.id, type: emp1.contractType, startDate: emp1.hireDate, endDate: emp1.contractType !== "INDEFINIDO" ? new Date("2025-12-31") : null, salary: emp1.salary, description: "Contrato " + emp1.contractType.toLowerCase().replace("_"," ") } }); }
  var skills = await Promise.all([prisma.skill.create({data:{name:"JavaScript",category:"Tecnica"}}),prisma.skill.create({data:{name:"Python",category:"Tecnica"}}),prisma.skill.create({data:{name:"React",category:"Tecnica"}}),prisma.skill.create({data:{name:"SQL",category:"Tecnica"}}),prisma.skill.create({data:{name:"Liderazgo",category:"Blanda"}}),prisma.skill.create({data:{name:"Comunicacion",category:"Blanda"}}),prisma.skill.create({data:{name:"Excel Avanzado",category:"Tecnica"}}),prisma.skill.create({data:{name:"Ingles B2",category:"Idioma"}}),prisma.skill.create({data:{name:"Gestion de Proyectos",category:"Blanda"}}),prisma.skill.create({data:{name:"Diseno UX/UI",category:"Tecnica"}})]);
  for (var si2 = 0; si2 < 8; si2++) { var empS = employees[si2]; var sh = skills.slice().sort(function(){return 0.5-Math.random()}).slice(0,2+Math.floor(Math.random()*3)); for (var sj = 0; sj < sh.length; sj++) { await prisma.employeeSkill.create({data:{employeeId:empS.id,skillId:sh[sj].id,level:1+Math.floor(Math.random()*5)}}); } }
  var today = new Date();
  for (var off = 1; off <= 5; off++) { var dd = new Date(today); dd.setDate(dd.getDate()-off); if (dd.getDay()===0||dd.getDay()===6) continue; for (var ai2=0;ai2<employees.length;ai2++){ var empA=employees[ai2]; var sts2=["PRESENTE","PRESENTE","PRESENTE","PRESENTE","TARDANZA","AUSENTE"]; var st=sts2[Math.floor(Math.random()*sts2.length)]; var cH=st==="TARDANZA"?9:8; var cM=Math.floor(Math.random()*30); var oM=Math.floor(Math.random()*30); var cin=st!=="AUSENTE"?new Date(dd.getFullYear(),dd.getMonth(),dd.getDate(),cH,cM):null; var cout=st!=="AUSENTE"?new Date(dd.getFullYear(),dd.getMonth(),dd.getDate(),18,oM):null; var hw=cin&&cout?Math.round(((cout-cin)/3600000)*100)/100:0; await prisma.attendance.create({data:{employeeId:empA.id,date:new Date(dd.getFullYear(),dd.getMonth(),dd.getDate()),status:st,checkIn:cin,checkOut:cout,hoursWorked:hw,overtime:Math.max(hw-8,0)}}); } }
  console.log("Asistencia ok");
  var lvSt=["PENDIENTE","APROBADA","APROBADA","RECHAZADA"];
  for(var li=0;li<12;li++){var empL=employees[Math.floor(Math.random()*employees.length)];var lt=leaveTypes[Math.floor(Math.random()*leaveTypes.length)];var sd=new Date(today);sd.setDate(sd.getDate()+Math.floor(Math.random()*30));var ed=new Date(sd);ed.setDate(ed.getDate()+1+Math.floor(Math.random()*5));var stL=lvSt[Math.floor(Math.random()*lvSt.length)];await prisma.leaveRequest.create({data:{employeeId:empL.id,leaveTypeId:lt.id,startDate:sd,endDate:ed,totalDays:Math.ceil((ed-sd)/86400000),reason:"Solicitud de "+lt.name.toLowerCase(),status:stL,approvedBy:stL!=="PENDIENTE"?employees[0].firstName+" "+employees[0].lastName:null,approvedAt:stL!=="PENDIENTE"?new Date():null}})}
  console.log("Permisos ok");
  for(var pi2=0;pi2<10;pi2++){var empP=employees[pi2];var base=empP.salary;var afp=Math.round(base*0.1271*100)/100;var hi=Math.round(base*0.10*100)/100;var tax=Math.round(Math.max((base-afp-2000)*0.13,0)*100)/100;var ded=afp+hi+tax;var net=Math.round((base-ded)*100)/100;await prisma.payroll.create({data:{employeeId:empP.id,period:"2025-03",month:3,year:2025,baseSalary:base,deductions:ded,tax:tax,afp:afp,healthIns:hi,netSalary:net,status:"PAGADO",paidAt:new Date("2025-03-28"),items:{create:[{concept:"Salario Base",type:"INGRESO",amount:base},{concept:"AFP 12.71%",type:"DESCUENTO",amount:afp},{concept:"Seguro Salud 10%",type:"DESCUENTO",amount:hi},{concept:"RC-IVA 13%",type:"DESCUENTO",amount:tax}]}}})}
  console.log("Planilla ok");
  for(var ri=0;ri<10;ri++){var empR=employees[ri];await prisma.performanceReview.create({data:{employeeId:empR.id,reviewerId:employees[1].id,period:"2024-S2",rating:3+Math.floor(Math.random()*3),strengths:"Excelente trabajo en equipo",improvements:"Mejorar gestion del tiempo",comments:"Buen desempeno"}});await prisma.performanceGoal.create({data:{employeeId:empR.id,title:"Completar certificacion tecnica",description:"Obtener certificacion",targetDate:new Date("2025-06-30"),progress:Math.floor(Math.random()*80)}});await prisma.performanceGoal.create({data:{employeeId:empR.id,title:"Mejorar productividad 15%",targetDate:new Date("2025-06-30"),progress:Math.floor(Math.random()*80)}})}
  console.log("Evaluaciones ok");
  var trainings=await Promise.all([prisma.training.create({data:{title:"Desarrollo Web Next.js 14",description:"Curso full-stack",instructor:"Ing. Roberto Paz",startDate:new Date("2025-02-01"),endDate:new Date("2025-03-15"),maxCapacity:15,isOnline:true}}),prisma.training.create({data:{title:"Liderazgo y Gestion",description:"Habilidades gerenciales",instructor:"Lic. Patricia Soliz",startDate:new Date("2025-03-01"),endDate:new Date("2025-04-30"),maxCapacity:20,isOnline:false,location:"Oficina Central"}}),prisma.training.create({data:{title:"Excel Avanzado y Power BI",description:"Analisis de datos",instructor:"Ing. Marco Aliaga",startDate:new Date("2025-04-01"),endDate:new Date("2025-04-30"),maxCapacity:25,isOnline:false,location:"Sala capacitacion"}}),prisma.training.create({data:{title:"Seguridad Informatica",description:"Ciberseguridad",instructor:"Ing. Sergio Villca",startDate:new Date("2025-05-15"),endDate:new Date("2025-06-15"),maxCapacity:15,isOnline:true}})]);
  for(var ti=0;ti<trainings.length;ti++){var tr=trainings[ti];var sh2=employees.slice().sort(function(){return 0.5-Math.random()}).slice(0,3+Math.floor(Math.random()*5));var sts3=["INSCRITO","EN_CURSO","COMPLETADO"];for(var sj2=0;sj2<sh2.length;sj2++){await prisma.trainingEnrollment.create({data:{trainingId:tr.id,employeeId:sh2[sj2].id,status:sts3[Math.floor(Math.random()*sts3.length)],completedAt:Math.random()>0.5?new Date():null}})}}
  console.log("Capacitaciones ok");
  var docCats=["IDENTIDAD","CONTRATO","CERTIFICADO","OTRO"];
  for(var di2=0;di2<12;di2++){var empD=employees[di2];for(var doci=0;doci<1+Math.floor(Math.random()*3);doci++){var cat=docCats[doci%docCats.length];await prisma.document.create({data:{employeeId:empD.id,title:cat+" - "+empD.firstName+" "+empD.lastName,category:cat,fileUrl:"/uploads/docs/"+empD.employeeCode+"_doc"+(doci+1)+".pdf",expiresAt:Math.random()>0.5?new Date(Date.now()+Math.random()*365*86400000):null}})}}
  console.log("Documentos ok");
  var expCats=["VIATICOS","TRANSPORTE","MATERIALES","REPRESENTACION","CAPACITACION","OTROS"];
  for(var xi=0;xi<15;xi++){var empX=employees[Math.floor(Math.random()*employees.length)];var xcat=expCats[Math.floor(Math.random()*expCats.length)];var xst=["ENVIADO","APROBADO","APROBADO","RECHAZADO"][Math.floor(Math.random()*4)];await prisma.expense.create({data:{employeeId:empX.id,category:xcat,amount:100+Math.floor(Math.random()*2000),description:"Gasto de "+xcat.toLowerCase(),date:new Date(Date.now()-Math.random()*30*86400000),status:xst,approvedBy:xst==="APROBADO"?employees[0].firstName+" "+employees[0].lastName:null}})}
  console.log("Gastos ok");
  var assetList=[{n:"MacBook Pro 14",c:"ACT-001",cat:"COMPUTADORA",v:12000},{n:"MacBook Pro 14",c:"ACT-002",cat:"COMPUTADORA",v:12000},{n:"Dell Monitor 27",c:"ACT-003",cat:"MONITOR",v:2500},{n:"Dell Monitor 27",c:"ACT-004",cat:"MONITOR",v:2500},{n:"iPhone 15 Pro",c:"ACT-005",cat:"CELULAR",v:7500},{n:"Silla Herman Miller",c:"ACT-006",cat:"MOBILIARIO",v:4500},{n:"Escritorio Electrico",c:"ACT-007",cat:"MOBILIARIO",v:3500},{n:"Impresora HP LaserJet",c:"ACT-008",cat:"IMPRESORA",v:5000},{n:"Proyector Epson",c:"ACT-009",cat:"AUDIOVISUAL",v:6000},{n:"ThinkPad T14s",c:"ACT-010",cat:"COMPUTADORA",v:8000}];
  for(var ai3=0;ai3<assetList.length;ai3++){var a=assetList[ai3];await prisma.asset.create({data:{name:a.n,code:a.c,category:a.cat,value:a.v,condition:ai3===7?"REGULAR":"BUENO",assignedTo:ai3<employees.length?employees[ai3].id:null,assignedAt:ai3<employees.length?new Date("2024-01-15"):null}})}
  console.log("Activos ok");
  await Promise.all([prisma.announcement.create({data:{title:"Nuevo horario de trabajo",content:"Horario de 08:30 a 18:30 para todas las sucursales.",priority:"ALTA",authorId:adminUser.id,expiresAt:new Date("2025-04-30")}}),prisma.announcement.create({data:{title:"Capacitacion obligatoria: Seguridad",content:"Completar curso de Seguridad Informatica antes del 30 de junio.",priority:"URGENTE",authorId:hrUser.id,expiresAt:new Date("2025-06-30")}}),prisma.announcement.create({data:{title:"Celebracion Dia del Trabajador",content:"Almuerzo especial el 1 de mayo.",priority:"NORMAL",authorId:hrUser.id,expiresAt:new Date("2025-05-02")}}),prisma.announcement.create({data:{title:"Resultados encuesta clima laboral",content:"87% de satisfaccion general.",priority:"NORMAL",authorId:adminUser.id}}),prisma.announcement.create({data:{title:"Actualizacion sistema planillas",content:"Nuevas tasas AFP y RC-IVA 2025.",priority:"ALTA",authorId:adminUser.id,expiresAt:new Date("2025-12-31")}})]);
  console.log("Anuncios ok");
  var jp1=await prisma.jobPosting.create({data:{title:"Desarrollador Full-Stack Senior",description:"Dev full-stack con React, Node.js",requirements:"5+ anos, TypeScript",salaryMin:9000,salaryMax:14000,status:"ABIERTA",departmentId:deps[0].id,closingDate:new Date("2025-05-15")}});
  var jp2=await prisma.jobPosting.create({data:{title:"Analista de Marketing Digital",description:"Gestion de campanas digitales",requirements:"3+ anos, Google Ads",salaryMin:5000,salaryMax:8000,status:"ABIERTA",departmentId:deps[3].id,closingDate:new Date("2025-05-30")}});
  var appNames=["Alejandro Villca Torres","Natalia Condori Paz","Marcos Huanca Quispe","Isabella Morales Cruz","Sebastian Choque Vega","Camila Aliaga Rojas"];
  var appSts=["RECIBIDO","EN_REVISION","ENTREVISTA","PRUEBA_TECNICA","SELECCIONADO"];
  for(var api2=0;api2<appNames.length;api2++){var nm=appNames[api2];var parts=nm.split(" ");await prisma.applicant.create({data:{jobPostingId:api2<4?jp1.id:jp2.id,fullName:nm,email:parts[0].toLowerCase()+"."+parts[1].toLowerCase()+"@gmail.com",phone:"+591 7"+Math.floor(1000000+Math.random()*9000000),resumeUrl:"/uploads/cv/"+parts.join("_").toLowerCase()+"_cv.pdf",status:appSts[Math.floor(Math.random()*appSts.length)]}})}
  console.log("Reclutamiento ok");
  for(var shi=0;shi<10;shi++){var empH=employees[shi];await prisma.salaryHistory.create({data:{employeeId:empH.id,oldSalary:Math.round(empH.salary*0.85),newSalary:empH.salary,reason:"Incremento salarial anual 2024",effectiveDate:new Date("2024-01-01")}})}
  await Promise.all([prisma.notification.create({data:{userId:adminUser.id,title:"Bienvenido a NovaTech RRHH",message:"Sistema configurado.",type:"INFO"}}),prisma.notification.create({data:{userId:hrUser.id,title:"3 solicitudes pendientes",message:"Solicitudes de permiso por revisar.",type:"WARNING"}}),prisma.notification.create({data:{userId:mgrUser.id,title:"Evaluacion pendiente",message:"Evaluar a 2 empleados.",type:"INFO"}})]);
  await Promise.all([prisma.activityLog.create({data:{userId:adminUser.id,action:"CREAR",entity:"CompanySettings",entityId:settings.id,details:"Configuracion inicial"}}),prisma.activityLog.create({data:{userId:hrUser.id,action:"CREAR",entity:"Employee",details:"Carga de 20 empleados"}}),prisma.activityLog.create({data:{userId:adminUser.id,action:"ACTUALIZAR",entity:"SystemConfig",details:"Tasas AFP/RC-IVA 2025"}})]);
  console.log("\nSeed completado!");
  console.log("Admin: admin@novatech.bo / admin123");
  console.log("RRHH: rrhh@novatech.bo / admin123");
  console.log("Gerente: gerente@novatech.bo / admin123");
}
main().catch(function(e){console.error("Error:",e);process.exit(1)}).finally(function(){prisma.$disconnect()});
